services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - secret-api-network
    env_file:
      - .env

  postgres:
    image: postgres:16-alpine
    container_name: secret-api-postgres
    environment:
      POSTGRES_DB: secret_db
      POSTGRES_USER: secret_user
      POSTGRES_PASSWORD: secretpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - secret-api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U laravel -d task_api" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  secret-api-network: